import type { User, Project } from '@/types'

export const DEMO_CREDENTIALS = {
  email: 'demo@zareshmeridian.com',
  password: 'Demo@ZM2025!',
}

export const DEMO_USER: User = {
  id: 'demo-user-001',
  email: DEMO_CREDENTIALS.email,
  full_name: 'Ika Rahmawati',
  phone: '+62 812 3456 7890',
  company: 'PT Demo Kreatif',
  interest_type: 'studio',
  email_verified_at: '2025-01-01T00:00:00Z',
  two_factor_enabled: false,
  status: 'active',
  role: 'client',
  created_at: '2025-01-01T00:00:00Z',
  updated_at: '2025-01-01T00:00:00Z',
}

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    client_id: 'demo-user-001',
    name: 'Rebrand & Social Media System',
    description: 'Paket lengkap: brand identity + strategi konten 3 bulan pertama',
    status: 'active',
    created_at: '2025-04-01T00:00:00Z',
    deliverables: [
      {
        id: 'del-001',
        project_id: 'proj-001',
        title: 'Brand Identity Deck',
        description: 'Logo, color palette, typography, brand guidelines (PDF 24 halaman)',
        file_url: '#',
        file_name: 'ZM_BrandDeck_v2.pdf',
        status: 'approved',
        revision_count: 1,
        max_free_revisions: 2,
        approved_at: '2025-04-20T10:00:00Z',
        created_at: '2025-04-10T00:00:00Z',
        updated_at: '2025-04-20T10:00:00Z',
      },
      {
        id: 'del-002',
        project_id: 'proj-001',
        title: 'Content Calendar — Mei 2025',
        description: 'Kalender konten Instagram + caption 30 hari, 3 topik pillar',
        file_url: '#',
        file_name: 'ContentCalendar_Mei2025.xlsx',
        status: 'in_review',
        revision_count: 0,
        max_free_revisions: 2,
        created_at: '2025-04-22T00:00:00Z',
        updated_at: '2025-04-22T00:00:00Z',
      },
      {
        id: 'del-003',
        project_id: 'proj-001',
        title: 'Email Welcome Sequence',
        description: '5-email nurture sequence untuk lead baru (copywriting + HTML template)',
        file_url: '#',
        file_name: 'EmailSequence_Welcome.zip',
        status: 'revision_requested',
        revision_count: 1,
        max_free_revisions: 2,
        created_at: '2025-04-15T00:00:00Z',
        updated_at: '2025-04-28T00:00:00Z',
      },
      {
        id: 'del-004',
        project_id: 'proj-001',
        title: 'Analytics Dashboard Setup',
        description: 'GA4 + Meta Pixel tracking + Looker Studio report template',
        status: 'pending',
        revision_count: 0,
        max_free_revisions: 2,
        created_at: '2025-04-01T00:00:00Z',
        updated_at: '2025-04-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'proj-002',
    client_id: 'demo-user-001',
    name: 'Meta Ads Campaign — Q2',
    description: 'Setup + pengelolaan Meta Ads selama 3 bulan (April–Juni 2025)',
    status: 'active',
    created_at: '2025-04-01T00:00:00Z',
    deliverables: [
      {
        id: 'del-005',
        project_id: 'proj-002',
        title: 'Ad Creatives Batch 1',
        description: '10 creative assets (story + feed) untuk campaign awareness',
        file_url: '#',
        file_name: 'AdCreatives_Batch1.zip',
        status: 'approved',
        revision_count: 2,
        max_free_revisions: 2,
        approved_at: '2025-04-18T00:00:00Z',
        created_at: '2025-04-05T00:00:00Z',
        updated_at: '2025-04-18T00:00:00Z',
      },
      {
        id: 'del-006',
        project_id: 'proj-002',
        title: 'Campaign Report — April',
        description: 'Laporan performa iklan April: reach, CTR, ROAS, rekomendasi',
        file_url: '#',
        file_name: 'CampaignReport_April2025.pdf',
        status: 'revised',
        revision_count: 1,
        max_free_revisions: 2,
        created_at: '2025-05-02T00:00:00Z',
        updated_at: '2025-05-05T00:00:00Z',
      },
    ],
  },
]

export const DEMO_REVISIONS: Record<string, import('@/types').Revision[]> = {
  'del-001': [
    {
      id: 'rev-001',
      deliverable_id: 'del-001',
      revision_number: 1,
      revision_type: 'Design',
      feedback: 'Warna gold-nya terlalu terang, mohon disesuaikan ke tone yang lebih warm dan earthy. Juga font untuk body text lebih baik menggunakan DM Sans.',
      is_additional: false,
      notes: 'Sudah disesuaikan: gold diubah ke #B8912A, body font diganti DM Sans 400.',
      submitted_at: '2025-04-15T09:00:00Z',
      implemented_at: '2025-04-17T14:00:00Z',
    },
  ],
  'del-003': [
    {
      id: 'rev-002',
      deliverable_id: 'del-003',
      revision_number: 1,
      revision_type: 'Content',
      feedback: 'Email pertama terlalu formal. Tolong buat tone-nya lebih personal dan hangat — seperti ngobrol dengan teman, bukan presentasi perusahaan.',
      is_additional: false,
      submitted_at: '2025-04-26T11:30:00Z',
    },
  ],
  'del-005': [
    {
      id: 'rev-003',
      deliverable_id: 'del-005',
      revision_number: 1,
      revision_type: 'Design',
      feedback: 'Ukuran teks CTA di story terlalu kecil. Tolong perbesar dan buat lebih kontras.',
      is_additional: false,
      notes: 'CTA text diperbesar 20%, kontras ditingkatkan dengan background overlay.',
      submitted_at: '2025-04-08T10:00:00Z',
      implemented_at: '2025-04-09T16:00:00Z',
    },
    {
      id: 'rev-004',
      deliverable_id: 'del-005',
      revision_number: 2,
      revision_type: 'Content',
      feedback: 'Copywriting di feed creative #3 kurang kuat. Headline perlu lebih benefit-driven.',
      is_additional: false,
      notes: 'Headline diubah ke format "pain → solution". Sudah diapprove.',
      submitted_at: '2025-04-11T09:00:00Z',
      implemented_at: '2025-04-12T15:00:00Z',
    },
  ],
  'del-006': [
    {
      id: 'rev-005',
      deliverable_id: 'del-006',
      revision_number: 1,
      revision_type: 'Structure',
      feedback: 'Bagian rekomendasi terlalu singkat. Tolong tambahkan penjelasan lebih detail untuk setiap rekomendasi dan masukkan angka benchmarknya.',
      is_additional: false,
      submitted_at: '2025-05-04T14:00:00Z',
    },
  ],
}
